// AUTO-GENERATED from the AdFixus target-account research sheet ("Company Scores" tab).
// Do not edit by hand - regenerate from the source sheet. Each entry is a real publisher
// AdFixus researches: vertical, anonymous audience share, Tranco rank, current identity-
// stack sophistication, the identity gap AdFixus wedges into, and the AdFixus hook. Facts
// are drawn from public BuiltWith / People Data Labs research, not private data.
import type { Vertical, Sophistication } from './verticals';

export interface KnownCompany {
  company: string;
  vertical: Vertical;
  /** Anonymous (non-logged-in) share of the audience, %. */
  anonPct: number;
  /** Best Tranco rank across the portfolio (lower = bigger reach). */
  tranco: number | null;
  sophistication: Sophistication;
  /** The identity gap AdFixus wedges into (research note). */
  identityGap: string | null;
  /** The AdFixus hook / recommended angle for this account. */
  angle: string | null;
}

export const KNOWN_COMPANIES: readonly KnownCompany[] = [
  { company: "Fandom", vertical: "entertainment", anonPct: 95, tranco: 529, sophistication: "vendor-stacked", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "Guardian", vertical: "news", anonPct: 95, tranco: 191, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across theguardian.com - alongside 1 rented third-party IDs (Criteo…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Vox Media (NY Mag, The Verge)", vertical: "lifestyle", anonPct: 95, tranco: 785, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across vox.com, theverge.com, nymag.com, vulture.com - alongside 1 rented third-party IDs (Permutive…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Forbes", vertical: "news", anonPct: 95, tranco: 201, sophistication: "light-stack", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Reuters", vertical: "news", anonPct: 95, tranco: 284, sophistication: "light-stack", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "NFL", vertical: "lifestyle", anonPct: 95, tranco: 3036, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across nfl.com - alongside 2 rented third-party IDs (Adobe Audience Manager, Criteo…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Bloomberg", vertical: "news", anonPct: 95, tranco: 375, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across bloomberg.com - alongside 5 rented third-party IDs (LiveRamp, Lotame, Neustar, Tapad, The Trade Desk…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Disney", vertical: "broadcast", anonPct: 95, tranco: 396, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across espn.com, abc.com, nationalgeographic.com, hulu.com - alongside 4 rented third-party IDs (Adobe Audience Manager, BlueKai, Criteo, ID5…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "BBC Studios", vertical: "broadcast", anonPct: 95, tranco: 209, sophistication: "light-stack", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Cox Automotive Inc.", vertical: "classifieds", anonPct: 95, tranco: 5552, sophistication: "vendor-stacked", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Motley Fool", vertical: "news", anonPct: 95, tranco: 3044, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "NerdWallet", vertical: "news", anonPct: 95, tranco: 4369, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Tripadvisor", vertical: "classifieds", anonPct: 95, tranco: 556, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "National Basketball Association (NBA)", vertical: "lifestyle", anonPct: 95, tranco: 1917, sophistication: "in-house platform + vendors", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Bisnow", vertical: "news", anonPct: 95, tranco: 33489, sophistication: "light-stack", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "Morning Brew", vertical: "news", anonPct: 95, tranco: 36230, sophistication: "vendor-stacked", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "Vevo", vertical: "entertainment", anonPct: 95, tranco: 29848, sophistication: "vendor-stacked", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "Daily Mail", vertical: "news", anonPct: 95, tranco: 367, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Fubo", vertical: "broadcast", anonPct: 95, tranco: 5641, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "People Inc. (Dotdash Meredith)", vertical: "lifestyle", anonPct: 95, tranco: 792, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "AMC Networks", vertical: "broadcast", anonPct: 95, tranco: 26951, sophistication: "greenfield", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Axel Springer / Business Insider", vertical: "news", anonPct: 70, tranco: 412, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "NBCUniversal", vertical: "broadcast", anonPct: 95, tranco: 349, sophistication: "light-stack", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across nbcnews.com, cnbc.com, today.com, eonline.com - alongside 17 rented third-party IDs (Adobe Audience Manager, BlueConic, BlueKai, Criteo, Experian…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Nexstar", vertical: "broadcast", anonPct: 95, tranco: 2252, sophistication: "vendor-stacked", identityGap: "7 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Penske Media", vertical: "entertainment", anonPct: 95, tranco: 2066, sophistication: "vendor-stacked", identityGap: "9 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "iHeartRadio", vertical: "broadcast", anonPct: 95, tranco: 2505, sophistication: "vendor-stacked", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across iheart.com - alongside 2 rented third-party IDs (LiveIntent, Segment…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Corus Entertainment", vertical: "broadcast", anonPct: 95, tranco: 3518, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "WebMD / Medscape (Internet Brands)", vertical: "lifestyle", anonPct: 95, tranco: 852, sophistication: "vendor-stacked", identityGap: "9 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "USNews", vertical: "news", anonPct: 95, tranco: 1253, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Beasley Media", vertical: "broadcast", anonPct: 95, tranco: 171769, sophistication: "greenfield", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Condé Nast", vertical: "lifestyle", anonPct: 80, tranco: 527, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across newyorker.com, vogue.com, wired.com, vanityfair.com - alongside 18 rented third-party IDs (Adobe Audience Manager, Audigent, BlueConic, BlueKai, Criteo…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "The Atlantic", vertical: "news", anonPct: 95, tranco: 949, sophistication: "vendor-stacked", identityGap: "7 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The Washington Post", vertical: "news", anonPct: 90, tranco: 359, sophistication: "vendor-stacked", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across washingtonpost.com - alongside 9 rented third-party IDs (Criteo, Experian, ID5, LiveRamp, Lotame…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "NASCAR", vertical: "lifestyle", anonPct: 95, tranco: 12864, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Nickelodeon", vertical: "broadcast", anonPct: 95, tranco: 16591, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Benzinga", vertical: "news", anonPct: 95, tranco: 5179, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Fox News Media", vertical: "news", anonPct: 95, tranco: 441, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across foxnews.com, foxbusiness.com, foxweather.com, outkick.com - alongside 17 rented third-party IDs (Adobe Audience Manager, Audigent, BlueKai, Criteo, Experian…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Seeking Alpha", vertical: "news", anonPct: 70, tranco: 3390, sophistication: "vendor-stacked", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "VentureBeat", vertical: "b2b", anonPct: 95, tranco: 2788, sophistication: "vendor-stacked", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Axios", vertical: "news", anonPct: 95, tranco: 2190, sophistication: "light-stack", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Gannett / USA Today", vertical: "news", anonPct: 95, tranco: 547, sophistication: "vendor-stacked", identityGap: "15 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Reddit, Inc.", vertical: "entertainment", anonPct: 95, tranco: 101, sophistication: "light-stack", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Ziff Davis", vertical: "b2b", anonPct: 95, tranco: 632, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Psychology Today", vertical: "lifestyle", anonPct: 95, tranco: 1125, sophistication: "greenfield", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "DIRECTV", vertical: "broadcast", anonPct: 95, tranco: 9387, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Nextdoor", vertical: "localnews", anonPct: 95, tranco: 2816, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Warner Bros Discovery", vertical: "broadcast", anonPct: 95, tranco: 182, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across cnn.com, bleacherreport.com, max.com, discovery.com - alongside 6 rented third-party IDs (Criteo, ID5, LiveRamp, Lotame, The Trade Desk…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "MLB", vertical: "lifestyle", anonPct: 95, tranco: 953, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across mlb.com, milb.com - alongside 8 rented third-party IDs (Adobe Audience Manager, LiveIntent, LiveRamp, Lotame, Neustar…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Newsmax Media", vertical: "news", anonPct: 95, tranco: 6681, sophistication: "light-stack", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Edmunds", vertical: "classifieds", anonPct: 95, tranco: 5965, sophistication: "greenfield", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "Time", vertical: "news", anonPct: 95, tranco: 525, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Paramount", vertical: "entertainment", anonPct: 95, tranco: 636, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across cbsnews.com, cbssports.com, cbs.com, pluto.tv - alongside 16 rented third-party IDs (Adobe Audience Manager, BlueConic, BlueKai, Criteo, Experian…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "APM", vertical: "news", anonPct: 95, tranco: 15971, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "CUMULUS MEDIA", vertical: "broadcast", anonPct: 95, tranco: 171702, sophistication: "greenfield", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "RetailMeNot", vertical: "lifestyle", anonPct: 95, tranco: 11248, sophistication: "light-stack", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The Associated Press", vertical: "news", anonPct: 95, tranco: 761, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Toronto Star", vertical: "news", anonPct: 95, tranco: 3893, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Flipboard", vertical: "news", anonPct: 95, tranco: 3186, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Slate Magazine", vertical: "news", anonPct: 95, tranco: 2243, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Fortune", vertical: "news", anonPct: 95, tranco: 1084, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Modern Luxury", vertical: "lifestyle", anonPct: 95, tranco: 45923, sophistication: "no-data", identityGap: "Unknown - do not claim they lack identity infrastructure in outreach.", angle: "Discovery-led angle: open with questions about their identity setup rather than assertions." },
  { company: "POLITICO", vertical: "news", anonPct: 95, tranco: 2035, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "PlayOn Sports", vertical: "news", anonPct: 95, tranco: 5356, sophistication: "light-stack", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "TechCrunch", vertical: "b2b", anonPct: 95, tranco: 637, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The New York Times", vertical: "lifestyle", anonPct: 60, tranco: 151, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across nytimes.com, theathletic.com - alongside 7 rented third-party IDs (Criteo, Experian, LiveRamp, Lotame, Neustar…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "theScore", vertical: "news", anonPct: 95, tranco: 8087, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Digital Trends Media Group", vertical: "b2b", anonPct: 95, tranco: 3327, sophistication: "vendor-stacked", identityGap: "6 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "WildBrain", vertical: "broadcast", anonPct: 95, tranco: 357898, sophistication: "greenfield", identityGap: "No durable identity layer on the dominant property - anonymous traffic is monetised on context alone and decays in Safari/ITP.", angle: "AdFixus gives them a publisher-owned durable anonymous ID from day one - first identity layer, no vendor lock-in, immediate addressability uplift." },
  { company: "Breaking Media", vertical: "b2b", anonPct: 95, tranco: 21542, sophistication: "no-data", identityGap: "Unknown - do not claim they lack identity infrastructure in outreach.", angle: "Discovery-led angle: open with questions about their identity setup rather than assertions." },
  { company: "Deseret News", vertical: "news", anonPct: 95, tranco: 11405, sophistication: "no-data", identityGap: "Unknown - do not claim they lack identity infrastructure in outreach.", angle: "Discovery-led angle: open with questions about their identity setup rather than assertions." },
  { company: "Hallmark Media", vertical: "broadcast", anonPct: 95, tranco: 17307, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "McClatchy Media", vertical: "localnews", anonPct: 95, tranco: 4583, sophistication: "vendor-heavy", identityGap: "16 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "PYMNTS", vertical: "news", anonPct: 95, tranco: 12353, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Spectrum News", vertical: "broadcast", anonPct: 95, tranco: 19223, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Crunchyroll", vertical: "entertainment", anonPct: 50, tranco: 2530, sophistication: "light-stack", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Heavy", vertical: "news", anonPct: 95, tranco: 13273, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "MediaNews Group", vertical: "localnews", anonPct: 95, tranco: 4846, sophistication: "vendor-heavy", identityGap: "17 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Recurrent Ventures", vertical: "lifestyle", anonPct: 95, tranco: 4267, sophistication: "vendor-heavy", identityGap: "17 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Red Ventures", vertical: "lifestyle", anonPct: 95, tranco: 3409, sophistication: "vendor-heavy", identityGap: "11 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Dow Jones / News Corp", vertical: "news", anonPct: 95, tranco: 1784, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across wsj.com, marketwatch.com, barrons.com - alongside 15 rented third-party IDs (Adobe Audience Manager, BlueKai, Criteo, Experian, LiveIntent…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "The Arena Group", vertical: "news", anonPct: 95, tranco: 3593, sophistication: "vendor-heavy", identityGap: "16 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The Daily Wire", vertical: "news", anonPct: 95, tranco: 17207, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "TelevisaUnivision", vertical: "broadcast", anonPct: 95, tranco: 7458, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across univision.com, vix.com - alongside 8 rented third-party IDs (BlueKai, Criteo, LiveIntent, Lytics, Permutive…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Refinery29", vertical: "lifestyle", anonPct: 95, tranco: 7228, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "BuzzFeed", vertical: "lifestyle", anonPct: 95, tranco: 1038, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across buzzfeed.com, huffpost.com, tasty.co - alongside 17 rented third-party IDs (Adobe Audience Manager, Audigent, BlueKai, Criteo, Experian…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "New York Post", vertical: "news", anonPct: 95, tranco: 1010, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "TEGNA", vertical: "broadcast", anonPct: 95, tranco: 16017, sophistication: "light-stack", identityGap: "1 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The Daily Beast", vertical: "news", anonPct: 95, tranco: 2977, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Rogers Sports & Media", vertical: "broadcast", anonPct: 95, tranco: 11237, sophistication: "vendor-heavy", identityGap: "14 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "TKO", vertical: "broadcast", anonPct: 95, tranco: 12882, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across wwe.com, ufc.com - alongside 14 rented third-party IDs (Adobe Audience Manager, BlueKai, Criteo, ID5, LiveIntent…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "LA Times", vertical: "news", anonPct: 95, tranco: 847, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Texas Monthly", vertical: "lifestyle", anonPct: 95, tranco: 16528, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Boston Globe", vertical: "news", anonPct: 95, tranco: 3391, sophistication: "vendor-heavy", identityGap: "16 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Hearst Magazines", vertical: "lifestyle", anonPct: 95, tranco: 3029, sophistication: "in-house platform + vendors", identityGap: "Their graph covers logged-in/known users; the durable-ID gap is the anonymous majority of web traffic across esquire.com, cosmopolitan.com, goodhousekeeping.com, delish.com - alongside 15 rented third-party IDs (Adobe Audience Manager, BlueKai, Criteo, Experian, ID5…).", angle: "AdFixus extends the existing first-party graph with a publisher-owned durable anonymous ID that persists across Safari/ITP and all browsers - incremental addressable reach on traffic the login graph can't see, without new vendor IDs." },
  { company: "Newsweek", vertical: "news", anonPct: 95, tranco: 1408, sophistication: "vendor-stacked", identityGap: "9 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The Globe and Mail", vertical: "news", anonPct: 85, tranco: 2572, sophistication: "vendor-heavy", identityGap: "14 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Tribune", vertical: "news", anonPct: 95, tranco: 2702, sophistication: "vendor-heavy", identityGap: "19 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Citywire USA", vertical: "news", anonPct: 70, tranco: 53013, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Seattle Times", vertical: "news", anonPct: 95, tranco: 3871, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "The Minnesota Star Tribune", vertical: "news", anonPct: 95, tranco: 4918, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "TimeOut", vertical: "lifestyle", anonPct: 95, tranco: 3519, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "WPT Enterprises, Inc.", vertical: "broadcast", anonPct: 95, tranco: 135525, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "BestReviews", vertical: "lifestyle", anonPct: 95, tranco: 27941, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Slickdeals", vertical: "classifieds", anonPct: 95, tranco: 10932, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "ADWEEK", vertical: "b2b", anonPct: 95, tranco: 4459, sophistication: "vendor-stacked", identityGap: "8 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "InvestingChannel", vertical: "news", anonPct: 95, tranco: 26371, sophistication: "light-stack", identityGap: "2 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Observer Media", vertical: "news", anonPct: 95, tranco: 6449, sophistication: "vendor-stacked", identityGap: "6 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Philadelphia Inquirer", vertical: "news", anonPct: 95, tranco: 5609, sophistication: "vendor-stacked", identityGap: "7 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Complex NTWRK", vertical: "entertainment", anonPct: 95, tranco: 7653, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Weigel Broadcasting", vertical: "broadcast", anonPct: 95, tranco: 59091, sophistication: "vendor-heavy", identityGap: "15 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Dallas Morning News", vertical: "news", anonPct: 95, tranco: 4928, sophistication: "vendor-stacked", identityGap: "7 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Graham Media Group", vertical: "broadcast", anonPct: 95, tranco: 18710, sophistication: "vendor-heavy", identityGap: "17 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Minute Media", vertical: "lifestyle", anonPct: 95, tranco: 3105, sophistication: "vendor-heavy", identityGap: "17 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Apartment Therapy", vertical: "news", anonPct: 95, tranco: 5428, sophistication: "vendor-stacked", identityGap: "5 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Static Media", vertical: "lifestyle", anonPct: 95, tranco: 12170, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "NESN", vertical: "broadcast", anonPct: 95, tranco: 33958, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "EstrellaTV", vertical: "broadcast", anonPct: 95, tranco: 380477, sophistication: "no-data", identityGap: "Unknown - do not claim they lack identity infrastructure in outreach.", angle: "Discovery-led angle: open with questions about their identity setup rather than assertions." },
  { company: "G/O", vertical: "news", anonPct: 95, tranco: 1883, sophistication: "vendor-heavy", identityGap: "13 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "LoveToKnow Media", vertical: "news", anonPct: 95, tranco: 10899, sophistication: "vendor-stacked", identityGap: "6 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Houston Chronicle", vertical: "news", anonPct: 95, tranco: 3356, sophistication: "vendor-stacked", identityGap: "7 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Audacy, Inc.", vertical: "broadcast", anonPct: 95, tranco: 11335, sophistication: "vendor-heavy", identityGap: "12 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Front Office Sports", vertical: "lifestyle", anonPct: 95, tranco: 42842, sophistication: "vendor-heavy", identityGap: "11 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Gray Media", vertical: "broadcast", anonPct: 95, tranco: 37201, sophistication: "vendor-heavy", identityGap: "14 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Brad's Deals", vertical: "lifestyle", anonPct: 95, tranco: 33567, sophistication: "vendor-stacked", identityGap: "4 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "EW Scripps", vertical: "broadcast", anonPct: 95, tranco: 23570, sophistication: "vendor-heavy", identityGap: "15 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "YES", vertical: "broadcast", anonPct: 95, tranco: 177785, sophistication: "vendor-stacked", identityGap: "3 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "ALM", vertical: "b2b", anonPct: 70, tranco: 8283, sophistication: "vendor-heavy", identityGap: "15 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Advance Local", vertical: "news", anonPct: 95, tranco: 5185, sophistication: "vendor-heavy", identityGap: "16 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Weatherbug", vertical: "news", anonPct: 95, tranco: 14062, sophistication: "vendor-stacked", identityGap: "9 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
  { company: "Cox Media Group", vertical: "broadcast", anonPct: 95, tranco: 6563, sophistication: "vendor-heavy", identityGap: "17 third-party ID vendors but no publisher-OWNED durable ID - fragmented match rates, Safari/ITP decay, and data leakage to vendors.", angle: "AdFixus consolidates rented vendor IDs into a publisher-owned durable anonymous ID - better match durability across browsers and full ownership of the identity asset." },
];

/** Registrable domain → index into KNOWN_COMPANIES. Sorted for stable diffs. */
export const DOMAIN_TO_COMPANY: Readonly<Record<string, number>> = {
  "11alive.com": 86,
  "90min.com": 112,
  "abc.com": 7,
  "abc15.com": 124,
  "adweek.com": 104,
  "ajc.com": 129,
  "al.com": 127,
  "allrecipes.com": 19,
  "amc.com": 20,
  "apnews.com": 55,
  "audacy.com": 120,
  "autoblog.com": 80,
  "autotrader.com": 9,
  "axios.com": 39,
  "azcentral.com": 40,
  "bankrate.com": 78,
  "barrons.com": 79,
  "bbc.com": 8,
  "bbgi.com": 29,
  "benzinga.com": 35,
  "bestreviews.com": 102,
  "billboard.com": 24,
  "bisnow.com": 14,
  "bleacherreport.com": 46,
  "bloomberg.com": 6,
  "bobvila.com": 77,
  "bonappetit.com": 30,
  "boston.com": 92,
  "bostonglobe.com": 92,
  "bostonherald.com": 76,
  "bradsdeals.com": 123,
  "breakingdefense.com": 68,
  "businessinsider.com": 21,
  "buzzfeed.com": 84,
  "cbs.com": 51,
  "cbsnews.com": 51,
  "cbssports.com": 51,
  "charlotteobserver.com": 71,
  "chicagotribune.com": 96,
  "chron.com": 119,
  "citytv.com": 88,
  "citywire.com": 97,
  "cleveland.com": 127,
  "clickondetroit.com": 111,
  "cnbc.com": 22,
  "cnet.com": 42,
  "cnn.com": 46,
  "complex.com": 108,
  "cosmopolitan.com": 93,
  "creditcards.com": 78,
  "crunchyroll.com": 74,
  "cumulus.com": 53,
  "dailymail.co.uk": 17,
  "dailywire.com": 81,
  "dallasnews.com": 110,
  "deadline.com": 24,
  "delish.com": 93,
  "denverpost.com": 76,
  "deseret.com": 69,
  "digitaltrends.com": 66,
  "directv.com": 44,
  "discovery.com": 46,
  "disneyplus.com": 7,
  "domino.com": 77,
  "eastbaytimes.com": 76,
  "eater.com": 2,
  "edmunds.com": 49,
  "elle.com": 93,
  "emedicinehealth.com": 27,
  "eonline.com": 22,
  "espn.com": 7,
  "esquire.com": 93,
  "estrellatv.com": 116,
  "etcanada.com": 26,
  "everydayhealth.com": 42,
  "fandom.com": 0,
  "flipboard.com": 57,
  "fool.com": 10,
  "forbes.com": 3,
  "fortune.com": 59,
  "foxbusiness.com": 36,
  "foxnews.com": 36,
  "foxweather.com": 36,
  "freep.com": 40,
  "frontofficesports.com": 121,
  "fubo.tv": 18,
  "futurism.com": 77,
  "gamespot.com": 0,
  "gizmodo.com": 117,
  "globalnews.ca": 26,
  "goodhousekeeping.com": 93,
  "gothamsports.com": 125,
  "gq.com": 30,
  "hallmark.com": 70,
  "heavy.com": 75,
  "heroesandicons.com": 109,
  "hollywoodreporter.com": 24,
  "huffpost.com": 84,
  "hulu.com": 7,
  "ign.com": 42,
  "iheart.com": 25,
  "inquirer.com": 107,
  "investingchannel.com": 105,
  "investopedia.com": 19,
  "kansascity.com": 71,
  "kbb.com": 9,
  "king5.com": 86,
  "kktv.com": 122,
  "kotaku.com": 117,
  "ksat.com": 111,
  "kxan.com": 23,
  "latimes.com": 90,
  "law.com": 126,
  "lifehacker.com": 42,
  "lonelyplanet.com": 78,
  "marketwatch.com": 79,
  "mashable.com": 42,
  "max.com": 46,
  "maxpreps.com": 62,
  "medscape.com": 27,
  "mensjournal.com": 80,
  "mentalfloss.com": 112,
  "mercurynews.com": 76,
  "metacritic.com": 0,
  "metro.co.uk": 17,
  "metv.com": 109,
  "miamiherald.com": 71,
  "milb.com": 47,
  "mlb.com": 47,
  "modernluxury.com": 60,
  "morningbrew.com": 15,
  "mprnews.org": 52,
  "msnbc.com": 22,
  "nascar.com": 33,
  "nationalgeographic.com": 7,
  "nba.com": 13,
  "nbcnews.com": 22,
  "nerdwallet.com": 11,
  "nesn.com": 115,
  "newsmax.com": 48,
  "newsnationnow.com": 23,
  "newsweek.com": 94,
  "newyorker.com": 30,
  "nextdoor.com": 45,
  "nfl.com": 5,
  "nick.com": 34,
  "nj.com": 127,
  "nydailynews.com": 96,
  "nymag.com": 2,
  "nypost.com": 85,
  "nytimes.com": 64,
  "observer.com": 106,
  "ocregister.com": 76,
  "oregonlive.com": 127,
  "orlandosentinel.com": 96,
  "outkick.com": 36,
  "parade.com": 80,
  "paramountplus.com": 51,
  "pcmag.com": 42,
  "peacocktv.com": 22,
  "people.com": 19,
  "pluto.tv": 51,
  "politico.com": 61,
  "popsci.com": 77,
  "psychologytoday.com": 43,
  "pymnts.com": 72,
  "reddit.com": 41,
  "refinery29.com": 83,
  "retailmenot.com": 54,
  "reuters.com": 4,
  "rollingstone.com": 24,
  "rxlist.com": 27,
  "sacbee.com": 71,
  "scrippsnews.com": 124,
  "seattletimes.com": 98,
  "seekingalpha.com": 37,
  "si.com": 112,
  "slashgear.com": 114,
  "slate.com": 58,
  "slickdeals.net": 103,
  "spectrumlocalnews.com": 73,
  "sportsnet.ca": 88,
  "startribune.com": 99,
  "startv.com": 109,
  "statnews.com": 92,
  "tasty.co": 84,
  "techcrunch.com": 63,
  "tegna.com": 86,
  "texasmonthly.com": 91,
  "theathletic.com": 64,
  "theatlantic.com": 31,
  "thecut.com": 2,
  "thedailybeast.com": 87,
  "thedrive.com": 77,
  "theglobeandmail.com": 95,
  "theguardian.com": 1,
  "thehill.com": 23,
  "thekitchn.com": 113,
  "theplayerstribune.com": 112,
  "thepointsguy.com": 78,
  "thescore.com": 65,
  "thespruce.com": 19,
  "thestar.com": 56,
  "thestreet.com": 80,
  "theverge.com": 2,
  "time.com": 50,
  "timeout.com": 100,
  "tntdrama.com": 46,
  "travelandleisure.com": 19,
  "tripadvisor.com": 12,
  "tubi.tv": 36,
  "tvguide.com": 0,
  "ufc.com": 89,
  "univision.com": 82,
  "usatoday.com": 40,
  "usnews.com": 28,
  "vanityfair.com": 30,
  "variety.com": 24,
  "venturebeat.com": 38,
  "verywellhealth.com": 19,
  "vevo.com": 16,
  "vix.com": 82,
  "vogue.com": 30,
  "vox.com": 2,
  "vulture.com": 2,
  "washingtonpost.com": 32,
  "weatherbug.com": 128,
  "webmd.com": 27,
  "westwoodone.com": 53,
  "wfaa.com": 86,
  "wfsb.com": 122,
  "wgntv.com": 23,
  "wildbrain.com": 67,
  "wired.com": 30,
  "worldpokertour.com": 101,
  "wsbtv.com": 129,
  "wsj.com": 79,
  "wwe.com": 89,
  "yourdictionary.com": 118,
};
